_action_groups:
    value:
        - <argparse._ArgumentGroup object at 0x7c44ba5945b0>
        - <argparse._ArgumentGroup object at 0x7c44ba529090>
_actions:
    value:
        - _HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None, default='==SUPPRESS==', type=None, choices=None, required=False, help='show this help message and exit', metavar=None)
        - _StoreAction(option_strings=['--batch_size'], dest='batch_size', nargs=None, const=None, default=128, type=<class 'int'>, choices=None, required=False, help=None, metavar=None)
        - _StoreAction(option_strings=['--epochs'], dest='epochs', nargs=None, const=None, default=10, type=<class 'int'>, choices=None, required=False, help=None, metavar=None)
        - _StoreAction(option_strings=['--model'], dest='model', nargs=None, const=None, default='ffn', type=<class 'str'>, choices=None, required=False, help=None, metavar=None)
        - _StoreAction(option_strings=['--checkpoint_dir'], dest='checkpoint_dir', nargs=None, const=None, default='./assets', type=<class 'str'>, choices=None, required=False, help=None, metavar=None)
_has_negative_number_optionals:
    value: []
_mutually_exclusive_groups:
    value: []
_negative_number_matcher:
    value: re.compile('^-\\d+$|^-\\d*\\.\\d+$')
_option_string_actions:
    value:
        --batch_size: _StoreAction(option_strings=['--batch_size'], dest='batch_size', nargs=None, const=None, default=128, type=<class 'int'>, choices=None, required=False, help=None, metavar=None)
        --checkpoint_dir: _StoreAction(option_strings=['--checkpoint_dir'], dest='checkpoint_dir', nargs=None, const=None, default='./assets', type=<class 'str'>, choices=None, required=False, help=None, metavar=None)
        --epochs: _StoreAction(option_strings=['--epochs'], dest='epochs', nargs=None, const=None, default=10, type=<class 'int'>, choices=None, required=False, help=None, metavar=None)
        --help: _HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None, default='==SUPPRESS==', type=None, choices=None, required=False, help='show this help message and exit', metavar=None)
        --model: _StoreAction(option_strings=['--model'], dest='model', nargs=None, const=None, default='ffn', type=<class 'str'>, choices=None, required=False, help=None, metavar=None)
        -h: _HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None, default='==SUPPRESS==', type=None, choices=None, required=False, help='show this help message and exit', metavar=None)
_optionals:
    value: <argparse._ArgumentGroup object at 0x7c44ba529090>
_positionals:
    value: <argparse._ArgumentGroup object at 0x7c44ba5945b0>
_registries:
    value:
        action:
            append: argparse._AppendAction
            append_const: argparse._AppendConstAction
            count: argparse._CountAction
            extend: argparse._ExtendAction
            help: argparse._HelpAction
            "null": argparse._StoreAction
            parsers: argparse._SubParsersAction
            store: argparse._StoreAction
            store_const: argparse._StoreConstAction
            store_false: argparse._StoreFalseAction
            store_true: argparse._StoreTrueAction
            version: argparse._VersionAction
        type:
            "null": argparse.ArgumentParser.__init__.<locals>.identity
_subparsers:
    value: null
_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "6": 4.17.0
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
add_help:
    value: true
allow_abbrev:
    value: true
argument_default:
    value: null
conflict_handler:
    value: error
description:
    value: null
epilog:
    value: null
exit_on_error:
    value: true
formatter_class:
    value: argparse.HelpFormatter
fromfile_prefix_chars:
    value: null
prefix_chars:
    value: '-'
prog:
    value: train.py
usage:
    value: null
